name: Deploy

on:
  push:
    branches:
      - main

env:
  UPIKOTH_PACKAGES_READ: ${{ secrets.UPIKOTH_PACKAGES_READ }}
  VITE_S3_ACCESS_DOMAIN_NAME: ${{ vars.VITE_S3_ACCESS_DOMAIN_NAME }}
  VITE_YANDEX_API_KEY: ${{ secrets.VITE_YANDEX_API_KEY }}

jobs:
  lint:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3

      - run: npm ci
      - run: npm run lint

  deploy-to-s3:
    needs: lint
    name: Deploy to s3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3

      - run: npm ci
      - run: npm run build

      - uses: MrMeison/yc-object-storage-action@v1
        with:
          accessKeyId: ${{ secrets.S3_ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          bucketName: ${{ secrets.S3_BUCKET_NAME }}
          sourceDir: ./dist
          clear: true
